In [1]:
# import necessary libraries
import numpy as np
import tensorflow as tf

### Training Phase

In [2]:
# load dataset
with open("srilanka.txt", 'r', encoding='utf-8') as file:
    cricket_history = file.read()

In [3]:
cricket_history[:500]

'Cricket in Sri Lanka holds a storied history, reflecting a blend of colonial legacy, grassroots development, and global success. As a national passion, cricket transcends boundaries, bringing together men, women, and individuals with special needs under a shared love for the game.\n\nEarly Beginnings\nIntroduced by British colonists in the 19th century, cricket initially thrived in Colombo and other urban areas. Matches between British officials and local clubs marked the early cricketing culture. '

In [4]:
tokenizer = tf.keras.preprocessing.text.Tokenizer()
tokenizer.fit_on_texts([cricket_history])

In [5]:
tokenizer.get_config()['filters']

'!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n'

In [6]:
tokenizer.get_config()['word_counts']

'{"cricket": 21, "in": 19, "sri": 13, "lanka": 9, "holds": 1, "a": 10, "storied": 1, "history": 1, "reflecting": 1, "blend": 1, "of": 7, "colonial": 1, "legacy": 3, "grassroots": 2, "development": 1, "and": 15, "global": 2, "success": 1, "as": 4, "national": 2, "passion": 2, "transcends": 1, "boundaries": 2, "bringing": 1, "together": 1, "men": 1, "women": 1, "individuals": 1, "with": 5, "special": 2, "needs": 2, "under": 1, "shared": 1, "love": 1, "for": 3, "the": 24, "game": 2, "early": 3, "beginnings": 1, "introduced": 1, "by": 4, "british": 2, "colonists": 1, "19th": 1, "century": 2, "initially": 2, "thrived": 1, "colombo": 2, "other": 1, "urban": 1, "areas": 1, "matches": 1, "between": 1, "officials": 1, "local": 2, "clubs": 2, "marked": 2, "cricketing": 3, "culture": 1, "club": 1, "ccc": 1, "established": 1, "1832": 1, "is": 3, "one": 1, "oldest": 1, "still": 1, "active": 1, "today": 1, "20th": 1, "schools": 1, "such": 2, "royal": 1, "college": 2, "st": 1, "thomas\'": 1, "began":

In [7]:
tokenizer.word_index

{'the': 1,
 'cricket': 2,
 'in': 3,
 'and': 4,
 'sri': 5,
 'a': 6,
 'lanka': 7,
 'of': 8,
 'to': 9,
 'with': 10,
 'as': 11,
 'by': 12,
 'like': 13,
 'international': 14,
 'legacy': 15,
 'for': 16,
 'early': 17,
 'cricketing': 18,
 'is': 19,
 'through': 20,
 "lanka's": 21,
 'cup': 22,
 'has': 23,
 'blind': 24,
 'grassroots': 25,
 'global': 26,
 'national': 27,
 'passion': 28,
 'boundaries': 29,
 'special': 30,
 'needs': 31,
 'game': 32,
 'british': 33,
 'century': 34,
 'initially': 35,
 'colombo': 36,
 'local': 37,
 'clubs': 38,
 'marked': 39,
 'such': 40,
 'college': 41,
 'gained': 42,
 'test': 43,
 'england': 44,
 'while': 45,
 'world': 46,
 'win': 47,
 "women's": 48,
 'team': 49,
 'players': 50,
 'inclusivity': 51,
 'efforts': 52,
 'visually': 53,
 'lanka’s': 54,
 'resilience': 55,
 'these': 56,
 'sport': 57,
 'challenges': 58,
 'holds': 59,
 'storied': 60,
 'history': 61,
 'reflecting': 62,
 'blend': 63,
 'colonial': 64,
 'development': 65,
 'success': 66,
 'transcends': 67,
 'bring

In [8]:
input_sequences = []
for sentence in cricket_history.split('\n'):
    token_list = tokenizer.texts_to_sequences([sentence])[0]
    for i in range(1, len(token_list)):
        sequence = token_list[:i+1]
        input_sequences.append(sequence)

In [9]:
input_sequences[:5]

[[2, 3], [2, 3, 5], [2, 3, 5, 7], [2, 3, 5, 7, 59], [2, 3, 5, 7, 59, 6]]

In [10]:
max_length = max([len(input_sequence) for input_sequence in input_sequences])
max_length

73

In [11]:
# add padding
input_sequences = np.array(tf.keras.preprocessing.sequence.pad_sequences(input_sequences, maxlen=max_length, padding='pre'))

In [12]:
input_sequences[1]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 2, 3, 5])

In [13]:
# divide dataset into feature set (X) and labels (y)
X = input_sequences[:, :-1]
y = input_sequences[:, -1]

In [14]:
X[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 2])

In [15]:
y

array([  3,   5,   7,  59,   6,  60,  61,  62,   6,  63,   8,  64,  15,
        25,  65,   4,  26,  66,  11,   6,  27,  28,   2,  67,  29,  68,
        69,  70,  71,   4,  72,  10,  30,  31,  73,   6,  74,  75,  16,
         1,  32,  76,  12,  33,  78,   3,   1,  79,  34,   2,  35,  80,
         3,  36,   4,  81,  82,  83,  84,  85,  33,  86,   4,  37,  38,
        39,   1,  17,  18,  87,   1,  36,   2,  88,  89,  90,   3,  91,
        19,  92,   8,   1,  93,  38,  94,  95,  96,  12,   1,  17,  97,
        34,  98,  40,  11,  99,  41,   4, 100, 101,  41, 102, 103, 104,
       105,  20, 106, 107,  13,   1, 108,   8,   1, 109,   4,  14, 111,
        21,  18, 112, 113, 114, 115, 116,   3, 117,   1, 118,  42,  43,
       119,   3, 120, 121, 122,  44,  45, 123, 124,   3,  43,   2, 125,
       126,   5,   7, 127, 128,   3,   1, 129, 130,   2,  46,  22, 131,
       132,   3,   1, 133, 134, 135,  47,  39,   5,   7,  11,   6, 136,
       137,   3,  14,   2,   2,   3,   5,   7,   5,   7,  48,   

In [16]:
# number of words
num_classes = len(tokenizer.word_index)+1

In [17]:
# one-hot encoding labels
y = np.array(tf.keras.utils.to_categorical(y, num_classes=num_classes))

In [18]:
y[1]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [19]:
# model building
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Embedding(num_classes, 80, input_length=max_length-1))
model.add(tf.keras.layers.LSTM(100))
model.add(tf.keras.layers.Dense(num_classes, activation='softmax'))

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 72, 80)            20000     
                                                                 
 lstm (LSTM)                 (None, 100)               72400     
                                                                 
 dense (Dense)               (None, 250)               25250     
                                                                 
Total params: 117650 (459.57 KB)
Trainable params: 117650 (459.57 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [22]:
# compile the model
model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

In [23]:
# model training
history = model.fit(X, y, epochs=100)

Epoch 1/100
14/14 [==============================] - 4s 68ms/step - loss: 5.5141 - accuracy: 0.0310
Epoch 2/100
14/14 [==============================] - 1s 64ms/step - loss: 5.3242 - accuracy: 0.0524
Epoch 3/100
14/14 [==============================] - 1s 54ms/step - loss: 5.1548 - accuracy: 0.0548
Epoch 4/100
14/14 [==============================] - 1s 60ms/step - loss: 5.1031 - accuracy: 0.0548
Epoch 5/100
14/14 [==============================] - 1s 58ms/step - loss: 5.0798 - accuracy: 0.0548
Epoch 6/100
14/14 [==============================] - 1s 59ms/step - loss: 5.0626 - accuracy: 0.0476
Epoch 7/100
14/14 [==============================] - 1s 51ms/step - loss: 5.0546 - accuracy: 0.0571
Epoch 8/100
14/14 [==============================] - 1s 59ms/step - loss: 5.0369 - accuracy: 0.0571
Epoch 9/100
14/14 [==============================] - 1s 59ms/step - loss: 5.0215 - accuracy: 0.0905
Epoch 10/100
14/14 [==============================] - 1s 52ms/step - loss: 4.9907 - accuracy: 0.0571

### Prediction Phase

In [26]:
input_text = "cricket begin"
for i in range(100):
    token_list = tokenizer.texts_to_sequences([input_text])[0]
    token_list = tf.keras.preprocessing.sequence.pad_sequences([token_list], maxlen=max_length-1, padding='pre')
    predicted = np.argmax(model.predict(token_list), axis=-1)
    output_word = ""
    for word, index in tokenizer.word_index.items():
        if index == predicted:
            output_word = word
            break
    input_text += " " + output_word

print(input_text)

1/1 [==============================] - 0s 19ms/step
cricket begin in sri lanka holds a storied history reflecting a blend of colonial legacy grassroots development and global success as a national passion cricket transcends boundaries bringing together men women and individuals with special needs under a shared love for the game the game the team cricket club ccc established in 1832 is one of the oldest clubs still active today by the early 20th century schools such as royal college and st thomas' college began fostering young talent through annual encounters like the battle of the blues blues blues of the blues as of the blues of the final win
